STRATEGY_NUMBER = 5
STRATEGY_NAME = "orb_vwap_reclaim"

SIMULATION_ONLY = True
PLACE_ALPACA_ORDERS = False

SYMBOLS = [
    "HOOD", "AMD", "TSLA", "QQQ", "NVDA",
    "PLTR", "COIN", "SOFI", "MARA", "RIVN",
    "AMZN", "MSFT", "META", "GOOGL", "NFLX"
]

OPENING_RANGE_MINUTES = 15
NO_TRADE_BEFORE = "09:45"
NO_NEW_TRADES_AFTER = "11:30"

MIN_RELATIVE_VOLUME = 2.0
MIN_BREAKOUT_VOLUME_MULTIPLE = 1.1

TARGET_R = 2.0
MAX_TRADES_PER_DAY = 5
MAX_TRADES_PER_SYMBOL_PER_DAY = 1

LOG_FILE = "orb_vwap_sim_log.csv"